Add introduce command
codewars/discord-bot pull request #2
Opened 2021-06-20 05:35 UTC by DonaldKellett

This command is only available to admins and mods.

- `?introduce @mention`: DM's the mentioned user with an introduction to Codewars and its Discord server. Falls back to mentioning the user in the channel if DM is not available.
- `?introduce @mention #help-solve`: DM's the mentioned user with guidelines on asking for help on solving Codewars Kata. Falls back to mentioning the user in the channel if DM is not available.
- `?introduce @mention #off-topic`: DM's the mentioned user with an introduction to the off-topic channel and general guidelines on participation. Falls back to mentioning the user in the channel if DM is not available.

I have implemented most of the suggestions from the previous pull request, except that the messages are currently hardcoded in the source code instead of in separate text files. It was mentioned that the text files containing the messages should be in a separate directory, but which directory should we put it in? Once we've agreed on that, I can move the message contents out into a separate directory and fix any remaining issues.

2021-06-20 10:53 UTC, DonaldKellett commented
`?introduce @mention #off-topic` has been replaced with `?introduce @mention #anything` in response to the renaming of the affected channel.

2021-06-21 01:09 UTC, kazk commented
> It was mentioned that the text files containing the messages should be in a separate directory, but which directory should we put it in?

Messages can be under `text/` next to the command. I think that makes the most sense.

2021-06-21 01:18 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +const INTRO = `Welcome to the Codewars Discord server!
I don't think we need this. We have `#readme` and users are shown these when they join too.

2021-06-21 01:26 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +const ANYTHING = `Welcome to #anything! You can discuss pretty much anything that is appropriate for all ages on this channel, whether related to programming or not. However, we ask you to respect a
Again, this isn't more than what everyone agreed on when joining the server and what's in `#readme`.

The only difference is

> - Nor is this a place to receive free help for completing your programming homework, project, assignment, etc. Similar measures apply as for advertising

What is the use case? I don't think we should be using this command when someone comments on that channel the first time. So, this must be used when they did something wrong. Then that should be a different command like `?warn` explaining what they did wrong.

2021-06-21 02:14 UTC, DonaldKellett commented
Thanks for the feedback! I suppose we just keep `?introduce @mention #help-solve` and perhaps add a `?warn` command in another pull request?

2021-06-21 04:14 UTC, DonaldKellett commented
I removed `?introduce @mention` and `?introduce @mention #anything` and moved the message contents for `?introduce @mention #help-solve` into a top-level directory `text/`. The reason I did not place `text/` alongside the source file for the command `introduce.ts` is because the compiled file `introduce.js` lives in a different directory from `introduce.ts` so I cannot just do `path.join(__dirname, 'text')` to access that directory (though it can be fixed by replacing `/src` with `/lib`). Is that fine by you?

2021-06-21 05:39 UTC, kazk commented
> The reason I did not place `text/` alongside the source file for the command `introduce.ts` is because ...

Oh I forgot about that, sorry. Yeah, that's fine.

2021-06-21 05:57 UTC, kazk requested changes

2021-06-21 05:57 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +    await message.channel.send(`<@${mention.id}> ${reply}`);
I don't want the verbose text showing up in the channel. Just link to the file on GitHub.

```text
@user, I couldn't DM you. See <https://github.com/codewars/discord-bot/blob/text/help-solve.md> instead.
```

2021-06-21 05:57 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +    reply = (await promises.readFile(dmPath)).toString();
Build a map of channel name to text once on load. It's not going to change.

2021-06-21 05:57 UTC, kazk commented on text/help-solve.txt
> +Welcome to #help-solve! For an optimal experience, please include the following information **in #help-solve** (not to me!):
Change this to `.md`? It's easier to read when DM failed.

2021-06-21 05:57 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +  if (typeof mention !== "object") return;
```suggestion
```
`CommandArg` is always an object.

2021-06-21 05:57 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +  if (typeof channelMention !== "object") return;
```suggestion
```

2021-06-21 06:29 UTC, DonaldKellett commented
Suggestions applied, please review

2021-06-21 23:43 UTC, kazk commented on text/help-solve.md
> +\`\`\`
```suggestion
\`\`\`javascript  
console.log("Hello World!");  
\`\`\`  
```

2021-06-21 23:54 UTC, kazk commented on src/events/message/commands/help/introduce.ts
> +import * as path from "path";
nit: I usually order imports like this: standard lib (Node.js modules), packages, then local. 

```suggestion
import { readFileSync } from "fs";
import * as path from "path";
import { Role, TextChannel } from "discord.js";
import { Message, CommandArg } from "../types";
```

2021-06-21 23:57 UTC, kazk approved these changes

2021-06-21 23:57 UTC, merged

2021-06-21 23:57 UTC, kazk commented
Thanks!