?rankup: Fixed regex and added "8kyu" to RANKTHRESHOLDS
codewars/discord-bot pull request #24
Opened 2022-01-18 15:07 UTC by Djacon

2022-01-18 16:07 UTC, Djacon commented
1. Fixed regex to correctly recognize "target" and "limit" 
2. Added "8kyu" to RANKTHRESHOLDS to fix the error with "--target=8kyu"
3. Replaced the quotation marks where needed

2022-01-19 00:14 UTC, kazk requested changes
Thanks, but I'm not sure if changing the quotes was necessary. There's also a bug.

2022-01-19 00:14 UTC, kazk commented on src/events/message/commands/fun/rankup.ts
> +to ${target}${lang ? ` in {lang}` : ""}`;
```suggestion
to ${target}${lang ? ` in ${lang}` : ""}`;
```

2022-01-19 00:16 UTC, kazk approved these changes

2022-01-19 00:17 UTC, merged